library(ape)
library(V.PhyloMaker)
library(phytools)
library(geiger)
library(Taxonstand)
#usé read.csv2 porque está separado por punto y comas y no por comas
example <- read.csv2("filo_m6.csv")

#con este código checkamos que los nombres de las especies estén bien
names_check <- traits_gls$sp
names_check
names_check <- gsub('_',' ',names_check)

checked <- TPL(names_check)
joint <- paste(checked$New.Genus,checked$New.Species)
new_names <- cbind(checked$Genus, checked$New.Genus, checked$Taxon, jointt) 
new_names <- as.data.frame(new_names)
new_names
new_names[new_names$V3 %in% new_names$joint,"joint"] <- "igual"

file_path <- paste("C:/Users/PERSONAL/Downloads/Tesis/Matrices/Matriz8/", "taxonstand_result.xlsx", sep= "")
write.xlsx(new_names, file_path, 
           password = NULL)

#phylo.maker=Generate phylogenies under three scenarios using user-specified 
#species list based on a backbone mega-tree (e.g. GBOTB.extended.tre)

#nodes.info.1=A data.frame; the genus- and family-level nodes information of 
#GBOTB.extended, which was generated by function build.nodes.1

tree.a <- phylo.maker(example, output.sp.list=TRUE)
tree.a <- tree.a$scenario.3
plotTree(tree.a)

#reporte resultado

#creamos un path apra guardar el archivo
file_path <- paste("C:/Users/PERSONAL/Downloads/Tesis/Matrices/Matriz8/", "_", "result.xlsx", sep= "")

#reportamos el resultado en un exel
write.xlsx(tree.a$species.list, file_path, password = NULL)
write.tree(tree.a$scenario.3, "Figure.1c.phy")

#------------------------------------------------------------------------------------------
#Plots para filogenia
setwd("C:/Users/PERSONAL/Downloads/Tesis/Matrices/Matriz8")
traits_exa<-read.csv2("Matriz_8_22-06-2022.csv")
traits_exa$gen <- NULL
traits_exa$fam <- NULL
tree_exa <- read.tree('Figure.1c.phy')
traits_exa <-traits_exa[match(tree_exa$tip.label, traits_exa$sp),]
row.names(traits_exa)<-traits_exa[,1]

traits_exa$Ground_tissue_fibres = as.integer(traits_exa$Ground_tissue_fibres)

traits_exa$Growth_Rings = as.factor(traits_exa$Growth_Rings)
traits_exa$Vessel_porosity = as.factor(traits_exa$Vessel_porosity)
traits_exa$Vessel_arangement = as.factor(traits_exa$Vessel_arangement)
traits_exa$Perforation_plates = as.factor(traits_exa$Perforation_plates)
traits_exa$Intervessel_pits_arregement = as.factor(traits_exa$Intervessel_pits_arregement)
traits_exa$Mean_tangential_diameter_of_vessel_lumina = as.factor(traits_exa$Mean_tangential_diameter_of_vessel_lumina)
traits_exa$Ground_tissue_fibres = as.factor(traits_exa$Ground_tissue_fibres)
traits_exa$Septa_in_fibers = as.factor(traits_exa$Septa_in_fibers)
traits_exa$Fibre_wall_thickness = as.factor(traits_exa$Fibre_wall_thickness)
traits_exa$Parenchyma_Paratracheal = as.factor(traits_exa$Parenchyma_Paratracheal)
traits_exa$Type_of_parenchyma_banding = as.factor(traits_exa$Type_of_parenchyma_banding)
traits_exa$Ray_width = as.factor(traits_exa$Ray_width)
traits_exa$Rays..cellular_composition = as.factor(traits_exa$Rays..cellular_composition)

traits_exa[is.na(traits_exa)] <- 0


filo1 <- plotTree(tree_exa,type="fan",lwd=1,ftype="off")

#quitamos los "_" en los nombres
traits <- gsub('_',' ',traits_exa$sp)
traits <-  unlist(traits)
traits_exa<-traits_exa[,-1]
traits_exa <- cbind(traits, traits_exa)

chk<-name.check(tree_exa,traits_exa)
summary(chk)

tree_exa_1<-drop.tip(tree_exa,chk$tree_not_data)
## pull out the morphological trait "tail spines"
tail.spines<-setNames(lizard.data$tail.spines,
                      rownames(lizard.data))



